
POST http://localhost:8008/demo/v1/chat/completions
Content-Type: application/json
X-API-Key: llmgw-HHZ6VPGTgk5mpeVOg9SLznLYPXlj8Y8t
X-Session-ID: demo-session-12345

{
    "messages": [{"role": "user", "content": "Am i really awesome!"}]
}

###
POST http://localhost:1234/v1/chat/completions
Content-Type: application/json
Authorization: Bearer sk-lm-krW8lnnb:8Wy0H7wdduhv6Dy6QCVT

{
  "model": "mistralai/ministral-3-3b",
  "messages": [{"role": "user", "content": "say i am awesome!"}],
  "max_tokens": 100
}
